#Nerf Farms Plugin
#This plugin is intended to allow server owners to have more control over what types of mob farms their players can use.
#For the purposes of this plugin, these rules will, by default, apply to mobs not killed by a player/player's pet. (Fall damage, crushing, drowning)
#Additional config options are listed below.
#References:
#Entities: https://jd.papermc.io/paper/1.19/org/bukkit/entity/package-summary.html
#Materials/Blocks: https://jd.papermc.io/paper/1.19/org/bukkit/Material.html
#Spawn Reasons: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
#Damage Types: https://purpurmc.org/javadoc/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html

#only change this if asked
debug: 0

require-path: true

#NOT CURRENTLY IN USE
require-open-surroundings: true

require-line-of-sight: true

only-nerf-hostiles: true

allow-projectile-damage: true

skeletons-can-damage-creepers: true

withers-can-damage-entities: true

#[DROPS|EXP|BOTH|NEITHER]

modification-type: "BOTH"

max-distance: 15

max-blacklisted-damage-percent: 75

bypass:
#- SILVERFISH

blacklisted-damage-types:
- BLOCK_EXPLOSION
- CONTACT
- CRAMMING
- DRAGON_BREATH
- DROWNING
- DRYOUT
- FALL
- FALLING_BLOCK
- FIRE
- FIRE_TICK
- FREEZE
- HOT_FLOOR
- LAVA
- LIGHTNING
- SUFFOCATION
- SUICIDE

whitelisted-spawn-types:
- CUSTOM

blacklisted-below:
- MAGMA_BLOCK
- HONEY_BLOCK
- LAVA

blacklisted-in:
- LAVA
- BUBBLE_COLUMN
- HONEY_BLOCK
