#Nerf Farms Plugin
#This plugin is intended to allow server owners to have more control over what types of mob farms their players can use.
#For the purposes of this plugin, these rules will, by default, apply to mobs not killed by a player/player's pet. (Fall damage, crushing, drowning)
#Additional config options are listed below.
#References:
#Entities: https://jd.papermc.io/paper/1.19/org/bukkit/entity/package-summary.html
#Materials/Blocks: https://jd.papermc.io/paper/1.19/org/bukkit/Material.html
#Spawn Reasons: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
#Damage Types: https://purpurmc.org/javadoc/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html

#only change this if asked
debug: false

only-nerf-hostiles: true

bypass:
  - SILVERFISH

#[DROPS|EXP|BOTH|NEITHER]

modification-type: "EXP"

require-path: false

require-line-of-sight: false

allow-projectile-damage: true

skeletons-can-damage-creepers: true

withers-can-damage-entities: true

max-distance: 15

max-disallowed-damage-percent: 75

disallowed-damage-types:
- FALL
- FALLING_BLOCK
- LAVA
- DROWNING

blacklisted-spawn-types:
- CUSTOM

blacklisted-below:
- MAGMA_BLOCK
- HONEY_BLOCK
- LAVA

blacklisted-in:
- LAVA
- BUBBLE_COLUMN
- HONEY_BLOCK
